### PR TITLE
App strings reworked

### PR DESCRIPTION
**Pull request by comradekingu**

### CODE REVIEW

**Comment by zoff99** [comment]
@comradekingu can you explain what you changed and why please?

**Comment by comradekingu** [comment]
@zoff99 Just the various text strings, and inadvertently the encoding to UTF-8.

**Comment by zoff99** [comment]
github does not show the diff because it thinks UTF-8 is a binary file :-(

**Comment by zoff99** [comment]
@comradekingu ok the changes look ok. have you tested them in the app, some strings are longer now and maybe will overlow buttons, or stuff will look weired?

and can we convert them all to UTF-8 ? or does that not work for XCode?

**Comment by comradekingu** [comment]
@zoff99 I just did the changes because I saw the app offered for translation on Weblate.
All other iOS projects I have seen have been UTF-8 for everything, so I don't know why UTF-16 is needed.
Feel free to copy them over to how they got to be UTF-16 in the first place and implement the changes you want.

**Comment by zoff99** [comment]
i will check it manually. thanks for making those improvents

**Pull request closed without merging**
