### PR TITLE
Revert autodownload change

### PR DESCRIPTION
**Pull request by Tha14**

### CODE REVIEW

**Comment by zoff99** [comment]
hm yeah. the issue is that when you disable autodownload people not familiar enough will never get any files.
do you have a solution for this standard case:

a person sends a photo and a message -> antidote will receive a push notification, and will stay awake for 3 minutes, a download will show -> user is somewhere not reacting to the push notification -> after 3 minutes the download will fail.
the sending party has no idea why their file sends always fail. receiver has no idea why download always fail.
both parties are frustrated and uninstall because it sucks.

**Comment by zoff99** [comment]
lets revert it for now, so that we can make a release. but keep discussing how to fix the user facing issue ...

**Comment by Tha14** [comment]
> hm yeah. the issue is that when you disable autodownload people not familiar enough will never get any files. do you have a solution for this standard case:
> 
> a person sends a photo and a message -> antidote will receive a push notification, and will stay awake for 3 minutes, a download will show -> user is somewhere not reacting to the push notification -> after 3 minutes the download will fail. the sending party has no idea why their file sends always fail. receiver has no idea why download always fail. both parties are frustrated and uninstall because it sucks.

Don't care, I'm not changing default behavior and especially for an option that is first in the list of settings. Also, not putting people at risk for it.

**Review by zoff99 — APPROVED** [review]

**Comment by zoff99** [comment]
autodownload = false wont save you from receiving something that you may not want, since you do not see the content until you have actually downloaded it.

**Pull request merged**
